# version: '3'

# services:
#   auth-client:
#     image: jaybhandari/eathappy:client 
#     working_dir: /app/auth-client
#     ports:
#       - "5173:5173"
#     environment:
#       - NODE_ENV=development
#     networks:
#       - frontend   

#   auth-server:
#     image: jaybhandari/eathappy:server 
#     working_dir: /app/auth-server
#     ports:
#       - "8000:8000"
   
#     depends_on:
#       - auth-client
#     networks:
#       - frontend  

# networks:
#   frontend:
     
version: '3'

services:
  frontend:
    container_name: foodstore-frontend 
    image: jaybhandari/eathappy:client 
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - frontend   

  backend:
    container_name: foodstore-backend  
    image: jaybhandari/eathappy:server
    working_dir: /app/backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    networks:
      - frontend  

networks:
  frontend:

